# Generated by Django 5.1.4 on 2025-01-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_imagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
