# Generated by Django 5.1.4 on 2025-01-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userdata_groups_userdata_is_active_userdata_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_staff',
        ),
    ]
