# Generated by Django 5.1.4 on 2025-01-27 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
