# Generated by Django 5.1.4 on 2025-01-30 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_customtoken_key_alter_customtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
