# Generated by Django 5.1.4 on 2025-01-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_customtoken_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
