# Generated by Django 5.1.4 on 2025-04-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_userdata_options_remove_userdata_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
