# Generated by Django 5.1.4 on 2025-05-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_imagepost_total_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
