# Generated by Django 5.1.4 on 2025-05-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_imagepost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
