# Generated by Django 5.1.4 on 2025-05-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
