# Generated by Django 5.1.4 on 2025-05-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_imagepost_total_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='total_likes',
            new_name='totallikes',
        ),
    ]
