# Generated by Django 5.1.4 on 2025-05-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_rename_total_likes_imagepost_totallikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='totallikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
