# Generated by Django 5.1.4 on 2025-05-25 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_imagepost_totallikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdata',
            name='userprofile',
            field=models.ImageField(default='uploads/default.jpg', upload_to='profile/'),
        ),
    ]
