# Generated by Django 5.1.4 on 2025-05-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_remove_userdata_userprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='username',
            new_name='user',
        ),
    ]
