# Generated by Django 5.1.4 on 2025-05-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_rename_username_imagepost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
