# Generated by Django 5.1.4 on 2025-05-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='uploads/defaults.jpg', upload_to='uploads/'),
        ),
    ]
