# Generated by Django 5.1.4 on 2025-05-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='profiles',
        ),
    ]
