# Generated by Django 5.1.4 on 2025-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_rename_profile_profile_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profiles',
            field=models.ImageField(default='uploads/defaults.jpg', upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
